cuda_graph_config:
  enable_padding: true
  batch_sizes:
    - 1
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 16
    - 24
    - 32
    - 48
    - 64
    - 96
    - 128
print_iter_log: false
enable_attention_dp: true
enable_chunked_prefill: false
